### ISSUE TITLE
Show invoice Fee with the invoice payment method

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/prestashop#11]
Fetch the invoice Fee and show it with the payment method for Billmate Invoice.

**Comment by joakim-combain** [comment]
This hasn't been set as fixed, but I checked it and there is an invoice fee in the module settings as well as when checking out there si an invoice fee. I assume this is fixed then? Assuming that I haven't misunderstood this issue.

**Comment by Boxedsolutions** [comment]
No its not yet fixed. The Idea is to show the invoice Fee with description for Billmate Invoice description

**Comment by Boxedsolutions** [comment]
@andyjohansson Do you have any styling ideas?

**Comment by andyjohansson** [comment]
See attached...
![styling_handling_fee_example](https://cloud.githubusercontent.com/assets/4968755/5864352/ac4f9b4a-a281-11e4-915b-256137a40d1c.png)

**Comment by Boxedsolutions** [comment]
Good :+1:

**Comment by andyjohansson** [comment]
PS. we need the change the text on all of these on all platforms.

**Comment by Boxedsolutions** [comment]
We need 2 templates. One legacy and one standard :)

**Comment by andyjohansson** [comment]
I don't follow...

**Comment by Boxedsolutions** [comment]
Regarding the changes in Theming in 1.6. It needs a different Markup and logos attached as a background with css. But before 1.6 Could we just use the regular template with some finetuning.

**Comment by andyjohansson** [comment]
Sound like a plan, let's do it :+1:

**Comment by andyjohansson** [comment]
This is fixed @Boxedsolutions? Can Joakim test this on both 1.4, 1.5 and 1.6?

**Comment by Boxedsolutions** [comment]
For now its not implemented in 1.4. Will fix later today

**Comment by andyjohansson** [comment]
Ok, the translation is not fixed yet?
![skarmavbild 2015-01-26 kl 10 42 12](https://cloud.githubusercontent.com/assets/4968755/5897760/1a400a68-a548-11e4-8084-0eebde1cad9d.png)

**Comment by Boxedsolutions** [comment]
Nope :(
If all goes well. I will do it today

**Comment by Boxedsolutions** [comment]
Shows on 1.4 also.

**Comment by joakim-combain** [comment]
Is this supposed to be assigned to me? Is this ready for test or?

**Comment by Boxedsolutions** [comment]
It can wait until translation maybe.

**Comment by andyjohansson** [comment]
Is this one translated and ready for test @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
No not yet. I aim to get the translations ready as soon as i Solved some other issues.

**Comment by andyjohansson** [comment]
Ok, then you should be assigned again :)

**Comment by Boxedsolutions** [comment]
Should be translated

**Comment by joakim-combain** [comment]
![order teststore2](https://cloud.githubusercontent.com/assets/10434920/5915939/bd1f3c5e-a60b-11e4-8e30-0a8f482c55b2.png)

You need to fix this one. ) is put in a new row. Try to fit it on one row otherwise it looks bad.

**Comment by Boxedsolutions** [comment]
What screen resolution do you have?

**Comment by andyjohansson** [comment]
And what browser?

**Comment by joakim-combain** [comment]
1366 x 768 I use Chrome.

**Comment by joakim-combain** [comment]
![order teststore3](https://cloud.githubusercontent.com/assets/10434920/5916012/74a4c4ca-a60c-11e4-9305-af0cbf493e4d.png)
![order teststore4](https://cloud.githubusercontent.com/assets/10434920/5916013/74aaf6d8-a60c-11e4-8f5f-09cf3b21e23e.png)

I found these as well. Might be related.

**Comment by Boxedsolutions** [comment]
Space is removed

**Comment by joakim-combain** [comment]
this issue is fixed.
