### ISSUE TITLE
Mobile Device - Problem change paymentmethod on mobilephones

### ISSUE THREAD

**Issue by victorauren** [Billmate/prestashop#212]
[SWE] När man lägger en order på en mobiltelefon, matar in alla uppgifter med hjälp av getAdress. Sedan väljer man faktura/delbetalning som betalmetod, och ändrar till kort/bank samtidigt som man suddar ut personnumret under faktura/delbetalning. Då skapas ett felmeddelande att man inte angivit något personnummer, se bild. Detta problem är testat på iPhone/Safari. Fungerar på Android med Chrome.

[ENG] I make an order on a cellphone and fill in all details and then choose Invoce as a paymentmethod. I erase the personal number and then choose cardpayment an error apperas that inform that their is no personal number entered. This error is tested on iPhone/Safari. Works on Android/Chrome. See attached image for more information. 
![image1](https://cloud.githubusercontent.com/assets/14887835/12234285/31e117ce-b86c-11e5-959a-73097103f752.PNG)

**Comment by Boxedsolutions** [comment]
Its maybe solved when we hide the ssn field when getAddress is active?

**Comment by victorauren** [comment]
I have reproduced the error. 
This is how I did it: 
I entered address-fields manually and by accident entered a phonenumber in the getAdress field. I pressed save and the I choose Invoice as the payment method to use. Here I couldn't enter my pno number, and when I pressed "buy" it said that the pno was enter incorrect. I then removed the phonenumber I enterned by accedent and saved. Try to buy again but it said pno was missing and I couldn't enter pno under Invoice option.

**Comment by victorauren** [comment]
Seems to only appear when using getAdress-function

**Comment by Boxedsolutions** [comment]
Should be solved

**Comment by victorauren** [comment]
Just to be clear, is it suppose to be hidden when getAdress-fucntion is activated? So if I leave the field blanc, the option still don't appears under invoice.

**Comment by victorauren** [comment]
This is not a problem anymore so I close this
