### ISSUE TITLE
Starting checkout, then removing all items, will then redirect to a 500 error. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/prestashop#394]
Would you attempt to start a checkout then open up a new tab, empty your cart, and then finish the checkout will you get redirected to a 500 error page. Would you then try to make a new purchase will you instead be redirected to a new page that just say "ok" and the order will not be completed. 

How to reproduce: 
1: Start a purchase and go to the final step of the checkout.
2: Open up a new tab. 
3: Go to the cart and remove all items so that your cart is entirely empty. 
4: Go back to the original tab. 
5: Finish the order. 
6: Attempt to make a second order in this original tab.

**Comment by andyjohansson** [comment]
Edge case and I'm unsure how we can avoid this scenario. I however think that we can avoid this if we use the native way and not try to reinvvent the wheel. I.e. we stick to PrestaShop native orderconfirmation and so on.
@OskarOstlund does the same behaviour occur if we use a built in payment method?

**Comment by OskarOstlund** [comment]
No error message, No rogue state, you are not even redirected to a successURL and are instead redirected to your order history and no order is created in the store.

**Comment by andyjohansson** [comment]
OK, then I think we need to take a look this one as well @KFoobar prior to the release of 3.8.

**Comment by KFoobar** [comment]
I can't reproduce this issue. I don't get a 500 error. 

It may have already been resolved by a commit from the last few days.

@OskarOstlund Please verify if this still is an issue.

**Comment by OskarOstlund** [comment]
I still get the error but that is only on my localhost version so this seems to be bound to people developing locally which seems to be a very minor situation.

**Comment by andyjohansson** [comment]
Agree. Let's see if this error pops up later on.
